#### Import Libraries

In [1]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

#### Load Raw Kaggle Dataset

In [2]:
df = pd.read_csv("students.csv")

print("Shape:", df.shape)
df.head()

Shape: (2000, 24)

,Student ID,Name,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,...,CTC (LPA),Alumni Path,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA
0,b37412a3-fa5c-40ca-b087-7109a47482d7,Amit,21.0,Male,MECH,6.99,0.0,70.45,"Literary Society, Robotics","C++, Machine Learning, Python, Java",...,0.00,NaN,8.34,5.24,6.06,7.81,7.18,7.04,8.26,5.99
1,65001423-faeb-4d19-a550-8ea26133a34d,Tina Ballard,19.0,Male,ECE,6.46,0.0,65.45,"Literary Society, Coding Club","C++, SQL, Web Development",...,0.00,NaN,7.37,6.37,6.45,5.99,6.55,6.99,6.46,5.52
2,228aaf1d-8710-4c8d-bfec-001b0df01f34,Meena,19.0,Female,CIVIL,7.08,0.0,84.79,Literary Society,"Data Science, SQL, Machine Learning",...,0.00,NaN,5.79,8.82,7.03,6.92,7.67,6.01,7.75,6.62
3,1aa67474-e200-4157-ad54-c95aaa4d52a8,Christopher Morales,23.0,Male,ECE,6.92,2.0,62.26,"Coding Club, Entrepreneurship Cell","Python, SQL, Java",...,5.89,Research,7.90,4.26,8.19,7.52,8.32,6.80,4.94,7.43
4,5122db4a-14c8-44d7-b2f4-e869f69d3dd7,Siddharth,20.0,Male,EEE,7.09,0.0,97.12,Robotics,"C++, SQL, Java, Python",...,0.00,NaN,6.86,6.24,7.64,7.15,5.91,6.18,8.19,8.54

#### Basic Dataset Info

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student ID         1999 non-null   str
 1   Name               2000 non-null   str
 2   Age                1999 non-null   float64
 3   Gender             1999 non-null   str
 4   Branch             1999 non-null   str
 5   Average GPA        1999 non-null   float64
 6   Backlogs           1999 non-null   float64
 7   Attendance (%)     1999 non-null   float64
 8   Clubs              1999 non-null   str
 9   Skills             1999 non-null   str
 10  Internship Done    1999 non-null   str
 11  Internship Domain  982 non-null    str
 12  Placement Status   1999 non-null   str
 13  Placement Domain   1032 non-null   str
 14  CTC (LPA)          1999 non-null   float64
 15  Alumni Path        1032 non-null   str
 16  Sem1 GPA           1999 non-null   float64
 17  Sem2 GPA           1999 non-null   float64
 18  Sem3 GPA           1999 non-null   float64
 19  Sem4 GPA           1999 non-null   float64
 20  Sem5 GPA           1999 non-null   float64
 21  Sem6 GPA           1999 non-null   float64
 22  Sem7 GPA           1999 non-null   float64
 23  Sem8 GPA           1999 non-null   float64
dtypes: float64(13), str(11)
memory usage: 375.1 KB

#### Check missing values

In [4]:
df.isnull().sum()

Student ID              1
Name                    0
Age                     1
Gender                  1
Branch                  1
Average GPA             1
Backlogs                1
Attendance (%)          1
Clubs                   1
Skills                  1
Internship Done         1
Internship Domain    1018
Placement Status        1
Placement Domain      968
CTC (LPA)               1
Alumni Path           968
Sem1 GPA                1
Sem2 GPA                1
Sem3 GPA                1
Sem4 GPA                1
Sem5 GPA                1
Sem6 GPA                1
Sem7 GPA                1
Sem8 GPA                1
dtype: int64

#### Drop Irrelevant Identifier Columns

In [5]:
drop_cols = ["Student ID", "Name"]

df.drop(columns=[c for c in drop_cols if c in df.columns], inplace=True)

#### Separate Categorical & Numeric Columns

In [6]:
categorical_cols = df.select_dtypes(include=["object", "string"]).columns
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

print("Categorical columns:")
print(categorical_cols)

print("\nNumeric columns:")
print(numeric_cols)

Categorical columns:
Index(['Gender', 'Branch', 'Clubs', 'Skills', 'Internship Done',
       'Internship Domain', 'Placement Status', 'Placement Domain',
       'Alumni Path'],
      dtype='str')

Numeric columns:
Index(['Age', 'Average GPA', 'Backlogs', 'Attendance (%)', 'CTC (LPA)',
       'Sem1 GPA', 'Sem2 GPA', 'Sem3 GPA', 'Sem4 GPA', 'Sem5 GPA', 'Sem6 GPA',
       'Sem7 GPA', 'Sem8 GPA'],
      dtype='str')

#### Handle Missing Values

In [8]:
# Numeric columns
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns
for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

#### Feature Engineering – Skills Count

In [9]:
if "Skills" in df.columns:
    df["Skill_Count"] = df["Skills"].apply(
        lambda x: len([s for s in str(x).split(",") if s.strip() != ""])
    )

#### Feature Engineering – Clubs Count

In [10]:
if "Clubs" in df.columns:
    df["Club_Count"] = df["Clubs"].apply(
        lambda x: len([c for c in str(x).split(",") if c.strip() != ""])
    )

#### Internship Encoding

In [11]:
if "Internship Done" in df.columns:
    df["Internship Done"] = df["Internship Done"].map({
        "Yes": 1,
        "No": 0,
        "Unknown": 0
    })

#### Placement Status Encoding

In [12]:
df["Placement Status"] = df["Placement Status"].map({
    "Placed": 1,
    "Not Placed": 0
})

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                2000 non-null   float64
 1   Gender             2000 non-null   str
 2   Branch             2000 non-null   str
 3   Average GPA        2000 non-null   float64
 4   Backlogs           2000 non-null   float64
 5   Attendance (%)     2000 non-null   float64
 6   Clubs              2000 non-null   str
 7   Skills             2000 non-null   str
 8   Internship Done    2000 non-null   int64
 9   Internship Domain  2000 non-null   str
 10  Placement Status   1999 non-null   float64
 11  Placement Domain   2000 non-null   str
 12  CTC (LPA)          2000 non-null   float64
 13  Alumni Path        2000 non-null   str
 14  Sem1 GPA           2000 non-null   float64
 15  Sem2 GPA           2000 non-null   float64
 16  Sem3 GPA           2000 non-null   float64
 17  Sem4 GPA           2000 non-null   float64
 18  Sem5 GPA           2000 non-null   float64
 19  Sem6 GPA           2000 non-null   float64
 20  Sem7 GPA           2000 non-null   float64
 21  Sem8 GPA           2000 non-null   float64
 22  Skill_Count        2000 non-null   int64
 23  Club_Count         2000 non-null   int64
dtypes: float64(14), int64(3), str(7)
memory usage: 375.1 KB

#### Save CLEAN EDA Dataset

In [15]:
df.to_csv("students_cleaned_for_eda.csv", index=False)

In [16]:
## Exploratory Data Analysis & Visualization

In [33]:
# Load cleaned dataset for EDA
df_eda = pd.read_csv("students_cleaned_for_eda.csv")
print("Cleaned Dataset Shape:", df_eda.shape)
print("\nDataset Preview:")
df_eda.head()

Cleaned Dataset Shape: (2000, 24)

Dataset Preview:

,Age,Gender,Branch,Average GPA,Backlogs,Attendance (%),Clubs,Skills,Internship Done,Internship Domain,...,Sem1 GPA,Sem2 GPA,Sem3 GPA,Sem4 GPA,Sem5 GPA,Sem6 GPA,Sem7 GPA,Sem8 GPA,Skill_Count,Club_Count
0,21.0,Male,MECH,6.99,0.0,70.45,"Literary Society, Robotics","C++, Machine Learning, Python, Java",1,Consulting,...,8.34,5.24,6.06,7.81,7.18,7.04,8.26,5.99,4,2
1,19.0,Male,ECE,6.46,0.0,65.45,"Literary Society, Coding Club","C++, SQL, Web Development",0,Unknown,...,7.37,6.37,6.45,5.99,6.55,6.99,6.46,5.52,3,2
2,19.0,Female,CIVIL,7.08,0.0,84.79,Literary Society,"Data Science, SQL, Machine Learning",1,Research,...,5.79,8.82,7.03,6.92,7.67,6.01,7.75,6.62,3,1
3,23.0,Male,ECE,6.92,2.0,62.26,"Coding Club, Entrepreneurship Cell","Python, SQL, Java",0,Unknown,...,7.90,4.26,8.19,7.52,8.32,6.80,4.94,7.43,3,2
4,20.0,Male,EEE,7.09,0.0,97.12,Robotics,"C++, SQL, Java, Python",1,Higher Studies,...,6.86,6.24,7.64,7.15,5.91,6.18,8.19,8.54,4,1

### 1. Bar Chart – Placement Status Distribution

In [18]:
placement_counts = df_eda['Placement Status'].value_counts()
fig = px.bar(x=placement_counts.index, y=placement_counts.values, 
             labels={'x': 'Placement Status', 'y': 'Count'},
             title='Placement Status Distribution',
             color=placement_counts.index,
             color_discrete_sequence=px.colors.qualitative.Set2)
fig.update_layout(showlegend=False, template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 2. Pie Chart – Placed vs Not Placed Ratio

In [19]:
placement_pie = df_eda['Placement Status'].value_counts()
fig = px.pie(names=placement_pie.index, values=placement_pie.values,
             title='Placed vs Not Placed Ratio',
             color_discrete_sequence=px.colors.qualitative.Pastel)
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 3. Box Plot – Mean GPA vs Placement Status

In [35]:
fig = px.box(df_eda, x='Placement Status', y='Average GPA', 
             title='Average GPA vs Placement Status',
             color='Placement Status',
             color_discrete_sequence=px.colors.qualitative.Bold)
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 4. Violin Plot – GPA Trend Distribution by Placement

In [36]:
fig = px.violin(df_eda, x='Placement Status', y='Average GPA',
                title='GPA Trend Distribution by Placement',
                color='Placement Status',
                color_discrete_sequence=px.colors.qualitative.Set1,
                box=True, points='outliers')
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 5. Histogram – Attendance Percentage Distribution

In [37]:
fig = px.histogram(df_eda, x='Attendance (%)', nbins=30,
                   title='Attendance Percentage Distribution',
                   color_discrete_sequence=['#FF6B6B'])
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12),
                  xaxis_title='Attendance (%)', yaxis_title='Count')
fig.show()

### 6. Scatter Plot – Mean GPA vs Skill Count

In [38]:
fig = px.scatter(df_eda, x='Average GPA', y='Skill_Count',
                 color='Placement Status',
                 title='Average GPA vs Skill Count',
                 color_discrete_sequence=px.colors.qualitative.Vivid,
                 size_max=10)
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 7. Bubble Chart – GPA vs Skills (Bubble Size = Attendance)

In [39]:
fig = px.scatter(df_eda, x='Average GPA', y='Skill_Count', 
                 size='Attendance (%)', color='Placement Status',
                 hover_name=None,
                 title='GPA vs Skills (Bubble Size = Attendance)',
                 color_discrete_sequence=px.colors.qualitative.Plotly)
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 8. Stacked Bar Chart – Internship Status vs Placement Outcome

In [40]:
internship_placement = df_eda.groupby(['Internship Done', 'Placement Status']).size().reset_index(name='count')
fig = px.bar(internship_placement, x='Internship Done', y='count', color='Placement Status',
             title='Internship Status vs Placement Outcome',
             color_discrete_sequence=px.colors.qualitative.Set2,
             barmode='stack')
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 9. Sunburst Chart – Branch-wise Placement Distribution

In [45]:
branch_placement = df_eda.groupby('Branch')['Placement Status'].value_counts().reset_index(name='count')
fig = px.sunburst(branch_placement, 
                  path=['Branch', 'Placement Status'], 
                  values='count',
                  color='count', 
                  color_continuous_scale='Viridis',
                  title='Branch-wise Placement Distribution')
fig.update_layout(template='plotly_dark', height=600, font=dict(size=12))
fig.show()

### 10. Treemap – Skill Count Contribution to Placement

In [46]:
skill_placement = df_eda.groupby('Skill_Count')['Placement Status'].value_counts().reset_index(name='count')
fig = px.treemap(skill_placement, 
                 path=['Skill_Count', 'Placement Status'], 
                 values='count',
                 color='count', 
                 color_continuous_scale='Plasma',
                 title='Skill Count Contribution to Placement')
fig.update_layout(template='plotly_dark', height=600, font=dict(size=12))
fig.show()

### 11. Heatmap – Feature Correlation Matrix

In [28]:
numeric_cols_list = df_eda.select_dtypes(include=['int64', 'float64']).columns.tolist()
corr_matrix = df_eda[numeric_cols_list].corr()
fig = go.Figure(data=go.Heatmap(z=corr_matrix.values, x=corr_matrix.columns, y=corr_matrix.columns,
                                colorscale='RdBu'))
fig.update_layout(title='Feature Correlation Matrix', template='plotly_dark', height=600, font=dict(size=11))
fig.show()

### 12. Line Chart – Semester-wise Average GPA Trend

In [29]:
semester_cols = [col for col in df_eda.columns if 'Sem' in col and 'GPA' in col]
if semester_cols:
    semester_avg = df_eda[semester_cols].mean()
    semester_nums = [col.split()[0] for col in semester_cols]
    fig = px.line(x=semester_nums, y=semester_avg.values,
                  title='Semester-wise Average GPA Trend',
                  markers=True, color_discrete_sequence=['#FF6B6B'])
    fig.update_layout(xaxis_title='Semester', yaxis_title='Average GPA', template='plotly_dark', height=500, font=dict(size=12))
    fig.show()
else:
    print("No semester GPA columns found")

### 13. Density Plot – GPA Distribution Density

In [42]:
fig = px.histogram(df_eda, x='Average GPA', nbins=40, histnorm='density',
                   title='GPA Distribution Density',
                   color_discrete_sequence=['#4ECDC4'],
                   marginal='box')
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12),
                  xaxis_title='Average GPA', yaxis_title='Density')
fig.show()

### 14. Funnel Chart – Student Journey to Placement

In [43]:
funnel_data = pd.DataFrame({
    'Stage': ['Total Students', 'High Attendance', 'Good GPA', 'With Skills', 'Placed'],
    'Count': [
        len(df_eda),
        len(df_eda[df_eda['Attendance (%)'] >= 75]),
        len(df_eda[df_eda['Average GPA'] >= 3.0]),
        len(df_eda[df_eda['Skill_Count'] >= 2]),
        len(df_eda[df_eda['Placement Status'] == 'Placed'])
    ]
})
fig = px.funnel(funnel_data, x='Count', y='Stage',
                title='Student Journey to Placement',
                color_discrete_sequence=['#FFD93D'])
fig.update_layout(template='plotly_dark', height=500, font=dict(size=12))
fig.show()

### 15. Radar Chart – Comparison of Placed vs Not Placed Profiles

In [44]:
placed = df_eda[df_eda['Placement Status'] == 'Placed']
not_placed = df_eda[df_eda['Placement Status'] != 'Placed']

categories = ['Average GPA', 'Skill Count', 'Attendance %', 'Club Count']
placed_vals = [
    placed['Average GPA'].mean() / 4.0 * 100,  # Normalize to 0-100 scale
    placed['Skill_Count'].mean() / 10 * 100,
    placed['Attendance (%)'].mean(),
    placed['Club_Count'].mean() / 5 * 100
]
not_placed_vals = [
    not_placed['Average GPA'].mean() / 4.0 * 100,
    not_placed['Skill_Count'].mean() / 10 * 100,
    not_placed['Attendance (%)'].mean(),
    not_placed['Club_Count'].mean() / 5 * 100
]

fig = go.Figure(data=[
    go.Scatterpolar(r=placed_vals, theta=categories, fill='toself', name='Placed', line=dict(color='#00CC96')),
    go.Scatterpolar(r=not_placed_vals, theta=categories, fill='toself', name='Not Placed', line=dict(color='#EF553B'))
])
fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 100])),
                  title='Comparison of Placed vs Not Placed Profiles',
                  template='plotly_dark', height=600, font=dict(size=12))
fig.show()